### ISSUE TITLE
No module named 'mujoco_py.mjlib'

### ISSUE THREAD

**Issue by donamin** [google-research/batch-ppo#5]
Hi.
I'm trying to run the code on Linux Mint.
With pendulum environment, it works perfectly. But when I try to run with Mujoco environments, I get the following error (I installed mujoco & mujoco-py):

```
Traceback (most recent call last):
  File "/home/amin/Projects/agents/agents/tools/wrappers.py", line 436, in _worker
    env = constructor()
  File "/home/amin/Projects/agents/agents/scripts/train.py", line 107, in <lambda>
    batch_env = utility.define_batch_env(lambda: _create_environment(config), config.num_agents, env_processes)
  File "/home/amin/Projects/agents/agents/scripts/train.py", line 47, in _create_environment
    env = gym.make(config.env)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/mujoco/mujoco_env.py", line 14, in <module>
    raise error.DependencyNotInstalled("{}. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)".format(e))
gym.error.DependencyNotInstalled: No module named 'mujoco_py.mjlib'. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)
```

**Comment by donamin** [comment]
I had to install an older version of mujoco_py with mujoco131

**Comment by AnandS09** [comment]
Is there any way to know what is causing the issue in the first place? I am getting the same issue on my mac and have followed all the instructions as mentioned in the README.md page.

The older version does not work with Mac as listed here: https://github.com/openai/gym/issues/638
